
# Fabric Properties | https://modmuss50.me/fabric.html
minecraft_version=1.21.1
parchment_version=parchment-1.21.1:2024.11.17
loader_version=0.16.14
fabric_version=0.116.4+1.21.1

# Mod Properties
mod_version=1.0
maven_group=com.weaversworkshop.grapplemod.compat
archives_base_name=grapplemod-compat-create

# Dependencies
grapplemod_target_range=>=2.0
create_version=6.0.9-215
create_target_range=>=6.0.9
neoforge_version=21.1.84

# Compilation Settings
show_dev_warnings=false
